artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  cache_dir: data/cache
  raw_data_dir: artifacts/data_ingestion/f1_stint_data_2020_2024.csv
  data_dir: data/f1_stint_data_2020_2024.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/f1_stint_data_2020_2024.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation
  model_path: artifacts/model_trainer
